# Generated by Django 5.1.3 on 2024-12-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diploma", "0002_coreclass_class_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diploma",
            name="classes_attempted",
        ),
        migrations.RemoveField(
            model_name="diploma",
            name="classes_completed",
        ),
        migrations.RemoveField(
            model_name="studentterm",
            name="student",
        ),
        migrations.RemoveField(
            model_name="term",
            name="in_progress",
        ),
        migrations.RemoveField(
            model_name="term",
            name="registered_for",
        ),
        migrations.AddField(
            model_name="studentterm",
            name="student_diploma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms_taken",
                to="diploma.studentdiploma",
            ),
        ),
        migrations.AlterField(
            model_name="diploma",
            name="GPA",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diploma",
            name="GPA2",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="StudentCoreClass",
            fields=[
                (
                    "coreclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diploma.coreclass",
                    ),
                ),
                (
                    "student_diploma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_taken",
                        to="diploma.studentdiploma",
                    ),
                ),
                (
                    "student_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_core_class",
                        to="diploma.studentterm",
                    ),
                ),
            ],
            bases=("diploma.coreclass",),
        ),
    ]
